### ISSUE TITLE
IR3:Airships stations have remote access blocked by RC

### ISSUE THREAD

**Issue by ghost** [tburrows13/RemoteConfiguration#2]
Hi there,

I've had a [report](https://github.com/Deadlock989/IndustrialRevolution/issues/340#issuecomment-1888085049) and confirmed that [airship stations](https://mods.factorio.com/mod/IndustrialRevolution3Airships) can't be opened remotely when RC is installed. Airship stations are a `simple-entity-with-force` so they have no native GUI of their own; the mod creates one when the entity is clicked on (at any distance, including zoomed in map mode) via on_gui_opened. Something in RC is preventing this from happening - at a guess I'd say it's line 78 in RC's control.lua? Not sure.

Can we work around this somehow? I notice there is an entity type blacklist. Since simple-entity-with-force doesn't have a native GUI, would it make sense to add it to the blacklist, since any GUI opened for such entities must always be scripted by some other mod? I've tested this and it appears to solve the immediate problem with Airships.

Cheers

**Comment by tburrows13** [comment]
Sorry for the delay. Fixed now in 1.2.6. (cc @mybuddymichael and @Nordblum)
